import bcrypt from "bcrypt";

const data = {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "john",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/pdt1.jpg",
      price: 120,
      countInStock: 5,
      brand: "Nike",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Shoe",
      category: "Shirts",
      image: "/images/pdt2.jpg",
      price: 120,
      countInStock: 10,

      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Shoe",
      category: "Shirts",
      image: "/images/pdt3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Heatset",
      category: "Shirts",
      image: "/images/pdt4.jpg",
      price: 120,
      brand: "Nike",
      countInStock: 0,
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Heatset",
      category: "Shirts",
      image: "/images/pdt5.jpg",
      price: 120,
      brand: "Nike",
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Heatset",
      category: "Shirts",
      image: "/images/pdt6.jpg",
      price: 120,
      brand: "Nike",
      countInStock: 20,
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Heatset",
      category: "Shirts",
      image: "/images/pdt7.jpg",
      price: 120,
      brand: "Nike",
      countInStock: 41,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Heatset",
      category: "Shirts",
      image: "/images/pdt8.jpg",
      price: 120,
      brand: "Nike",
      countInStock: 17,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Heatset",
      category: "Shirts",
      image: "/images/pdt9.jpg",
      price: 120,
      brand: "Nike",
      countInStock: 30,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Heatset",
      category: "Shirts",
      image: "/images/pdt10.jpg",
      price: 120,
      brand: "Nike",
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
